# Generated by Django 6.0.2 on 2026-02-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_question_test_remove_results_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='attempt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.testattempts'),
            preserve_default=False,
        ),
    ]
